FROM java:8-jre
MAINTAINER Yao y3tu <y3tu.vip@qq.com>

ADD ./jar/yao-authentication*.jar /app/app.jar

EXPOSE 9002

ENV JAVA_OPTS="-Xmx256m -Xms256m"
ENV CONFIG_PROFILE=prod
ENV AUTHENTICATION_PORT = 9002

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS \
-Dfile.encoding=UTF8 -Duser.timezone=GMT+08 \
-jar /app/app.jar \
--spring.profiles.active=$CONFIG_PROFILE \
--server.port=$AUTHENTICATION_PORT"]
