FROM java:8-jre
MAINTAINER Y3tu-Cloud y3tu <y3tu.vip@qq.com>

ADD ./jar/y3tu-cloud-gateway-*.jar /app/app.jar

EXPOSE 2019

ENV JAVA_OPTS="-Xmx256m -Xms256m"
ENV CONFIG_PROFILE=dev
ENV GATEWAY_PORT = 2019

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS \
-Dfile.encoding=UTF8 -Duser.timezone=GMT+08 \
-jar /app/app.jar \
--spring.profiles.active=$CONFIG_PROFILE \
--server.port=$GATEWAY_PORT"]
