FROM java:8-jre
MAINTAINER Yao y3tu <y3tu.vip@qq.com>

ADD ./jar/yao-authorization*.jar /app/app.jar

EXPOSE 9003

ENV JAVA_OPTS="-Xmx256m -Xms256m"
ENV CONFIG_PROFILE=dev
ENV AUTHORIZATION_PORT = 9003

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS \
-Dfile.encoding=UTF8 -Duser.timezone=GMT+08 \
-jar /app/app.jar \
--spring.profiles.active=$CONFIG_PROFILE \
--server.port=$AUTHORIZATION_PORT"]
